# Generated by Django 3.2.15 on 2023-01-16 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tank',
            options={'ordering': ['-time_create'], 'verbose_name': 'Танк', 'verbose_name_plural': 'Танки'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanks.tank', verbose_name='Танк'),
        ),
    ]
